# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d105966643c5a881b947993414021bd4fac3f80f8677dc91cf04bc6290a231ffb31d603a5d83ae5b134b156feb873ed34a51d34c495949e9648e9c338f6271b1

test:
  secret_key_base: 04e6b55e36f4a80c94488a34b94d72d28ccdfe78c6a52d4a17b0c2f610d998c474fcefdea8bdbe8b7e7b562b58852346bdfc326c8844c5ff0867bf61fdc5c287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
